#!/bin/bash

# Script to resolve merge conflicts by taking am-labs versions
echo "Resolving merge conflicts by taking am-labs versions..."

# List of files to resolve by taking am-labs version
files=(
    "src/__init__.py"
    "src/__main__.py"
    "src/agents/common/dependencies_helper.py"
    "src/agents/common/memory_handler.py"
    "src/agents/common/message_parser.py"
    "src/agents/common/session_manager.py"
    "src/agents/common/tool_registry.py"
    "src/agents/models/agent.py"
    "src/agents/models/agent_factory.py"
    "src/agents/models/placeholder.py"
    "src/agents/models/response.py"
    "src/agents/simple/__init__.py"
    "src/api/controllers/agent_controller.py"
    "src/api/controllers/session_controller.py"
    "src/api/controllers/user_controller.py"
    "src/api/docs.py"
    "src/api/memory_models.py"
    "src/api/memory_routes.py"
    "src/api/models.py"
    "src/api/routes/__init__.py"
    "src/api/routes/agent_routes.py"
    "src/api/routes/session_routes.py"
    "src/api/routes/user_routes.py"
    "src/auth.py"
    "src/cli/__init__.py"
    "src/cli/agent/__init__.py"
    "src/cli/agent/chat.py"
    "src/cli/agent/create.py"
    "src/cli/agent/run.py"
    "src/cli/db.py"
    "src/constants.py"
    "src/db/connection.py"
    "src/db/migrations/20250326_045944_add_channel_payload_to_messages.sql"
    "src/db/models.py"
    "src/db/repository.py"
    "src/db/repository/__init__.py"
    "src/db/repository/agent.py"
    "src/db/repository/memory.py"
    "src/db/repository/message.py"
    "src/db/repository/session.py"
    "src/db/repository/user.py"
    "src/memory/message_history.py"
    "src/tools/__init__.py"
    "src/tools/datetime/tool.py"
    "src/tools/discord/tool.py"
    "src/tools/evolution/__init__.py"
    "src/tools/evolution/interface.py"
    "src/tools/evolution/schema.py"
    "src/tools/evolution/tool.py"
    "src/tools/gmail/interface.py"
    "src/tools/gmail/tool.py"
    "src/tools/google_drive/schema.py"
    "src/tools/google_drive/tool.py"
    "src/tools/memory/interface.py"
    "src/tools/memory/provider.py"
    "src/tools/memory/schema.py"
    "src/tools/memory/tool.py"
    "src/tools/notion/interface.py"
    "src/tools/notion/tool.py"
    "src/utils/logging.py"
    "src/utils/multimodal.py"
    "src/version.py"
    "tests/api/test_agent_routes.py"
    "tests/api/test_session_routes.py"
    "tests/conftest.py"
    "tests/memory_system_test.py"
    "tests/test_agent_common_utils.py"
    "tests/test_memory_tools.py"
    "tests/test_new_message_history.py"
    "tests/test_simple_agent_dependencies.py"
    "tests/test_simple_agent_tools.py"
    "tests/tools/gmail/test_integration.py"
    ".aidigestignore"
    "pytest.ini"
)

# Process each file
for file in "${files[@]}"; do
    echo "Resolving $file..."
    git show am-labs/public-sync-clean:"$file" > "$file" 2>/dev/null
    if [ $? -eq 0 ]; then
        git add "$file"
        echo "✓ Resolved $file"
    else
        echo "⚠ Could not resolve $file (may not exist in am-labs branch)"
    fi
done

echo "Conflict resolution completed!"
echo "Remaining files to check manually:"
git status --porcelain | grep "^UU" 