version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: automagik_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - automagik_postgres_data:/var/lib/postgresql/data
    restart: always

  neo4j:
    image: neo4j:5
    container_name: automagik_neo4j
    ports:
      - "7474:7474"  # HTTP interface
      - "${NEO4J_PORT:-7687}:7687"  # Bolt interface
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-your_neo4j_password_here}
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME:-neo4j} -p ${NEO4J_PASSWORD:-your_neo4j_password_here} 'RETURN 1' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always

  graphiti:
    image: zepai/graphiti:latest
    container_name: automagik_graphiti
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USER=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-your_neo4j_password_here}
      - GRAPHITI_NAMESPACE_ID=${GRAPHITI_NAMESPACE_ID:-automagik}
      - GRAPHITI_ENV=${GRAPHITI_ENV:-development}
    depends_on:
      neo4j:
        condition: service_healthy
    restart: always

volumes:
  automagik_postgres_data:
  neo4j_data: 