name: CI

on:
  push:
    branches: [ main ] # Add other main branches if necessary, e.g., [ main, dev ]
  pull_request:
    branches: [ main ] # Add other main branches if necessary

jobs:
  lint_and_format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version
      - name: Get uv cache directory path
        id: uv-cache-path
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run Linter (Ruff)
        run: make lint
      - name: Check Formatter (Ruff)
        run: make format ARGS=--check

  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version
      - name: Get uv cache directory path
        id: uv-cache-path
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: uv sync --frozen
      - name: Audit Dependencies
        run: uv run pip-audit
      - name: Run Bandit Security Analysis
        run: 'uv run bandit -r src/ -c pyproject.toml --quiet --format=custom --msg-template "{abspath}:{line}: {test_id}[{severity}][{confidence}]: {msg}"'

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version
      - name: Get uv cache directory path
        id: uv-cache-path
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run Pytest with Coverage
        env:
          AM_API_KEY: "test_am_api_key_placeholder"
          OPENAI_API_KEY: "test_openai_api_key_placeholder"
          DISCORD_BOT_TOKEN: "test_discord_bot_token_placeholder"
        run: uv run pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: error 

  type_check:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version
      - name: Get uv cache directory path
        id: uv-cache-path
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |-
            ${{ runner.os }}-uv-
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run Mypy
        run: uv run mypy src/ 

  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: automagik-agents:latest
          # build-args: |
          #   ARG_NAME=value
          # labels: |
          #   org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }} 

  build_and_deploy_docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest
    # Só roda em pushes para a branch main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write # Necessário para fazer push para a branch gh-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para obter histórico para alguns geradores de docs/changelog

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv --version

      - name: Get uv cache directory path
        id: uv-cache-path
        run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-docs-${{ hashFiles('**/uv.lock') }}
          restore-keys: |-
            ${{ runner.os }}-uv-docs-

      - name: Install dependencies (including Sphinx)
        run: uv sync --frozen

      - name: Build Sphinx Documentation
        # O -W transforma warnings em erros, garantindo qualidade
        run: uv run sphinx-build -b html -W --keep-going docs/ build/docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs
          # Opcional: se você quiser um domínio customizado
          # cname: docs.meudominio.com 

  label_pr_conventional:
    name: Label PR (Conventional Commits)
    runs-on: ubuntu-latest
    # Roda em pull_request_target para permitir adicionar labels em PRs de forks
    if: github.event_name == 'pull_request_target'
    permissions:
      pull-requests: write # Necessário para adicionar/remover labels
      contents: read       # Necessário para ler os commits da PR
    steps:
      - name: Label PR based on Conventional Commits
        uses: mheap/conventional-pr-labels-action@v3
        env: # Usamos 'env' para definir as variáveis que a action lerá
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Mapeamento de tipos de commit para labels
          # Formato: CONVENTIONAL_PR_LABEL_<TIPO_COMMIT_EM_MAIUSCULAS>=<label>
          CONVENTIONAL_PR_LABEL_FEAT: "enhancement"
          CONVENTIONAL_PR_LABEL_FIX: "bug"
          CONVENTIONAL_PR_LABEL_DOCS: "documentation"
          CONVENTIONAL_PR_LABEL_STYLE: "style"
          CONVENTIONAL_PR_LABEL_REFACTOR: "refactor"
          CONVENTIONAL_PR_LABEL_PERF: "performance"
          CONVENTIONAL_PR_LABEL_TEST: "test"
          CONVENTIONAL_PR_LABEL_BUILD: "build"
          # Para ignorar 'chore', simplesmente não definimos CONVENTIONAL_PR_LABEL_CHORE
        with:
          skip_label_if_present: "ignore-for-release" 