name: Lint and Format Check

on:
  push:
    branches: [ main ] # Add other main branches if necessary, e.g., [ main, dev ]
  pull_request:
    branches: [ main ] # Add other main branches if necessary

jobs:
  lint_and_format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Adjust Python version according to your pyproject.toml

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync --frozen # or just uv sync if uv.lock is not always up-to-date

    - name: Run Linter (Ruff)
      run: make lint

    - name: Check Formatter (Ruff)
      run: make format ARGS=--check # Passes --check to the ruff format command within the Makefile 