name: Lint, Format, and Test Checks

on:
  push:
    branches: [ main ] # Add other main branches if necessary, e.g., [ main, dev ]
  pull_request:
    branches: [ main ] # Add other main branches if necessary

jobs:
  build_and_test:
    name: Build, Lint, Format & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Adjust Python version according to your pyproject.toml

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Add uv to PATH
      # Ensure uv is in PATH for subsequent steps, including uv cache dir
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        uv --version # Verify uv installation

    - name: Get uv cache directory path
      id: uv-cache-path
      # Ensure uv is available and in PATH before running this
      run: echo "UV_CACHE_DIR=$(uv cache dir)" >> $GITHUB_ENV

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install dependencies
      run: uv sync --frozen

    - name: Audit Dependencies
      run: uv run pip-audit

    - name: Run Linter (Ruff)
      run: make lint

    - name: Check Formatter (Ruff)
      run: make format ARGS=--check # Passes --check to the ruff format command within the Makefile

    - name: Run Pytest with Coverage
      env:
        AM_API_KEY: "test_am_api_key_placeholder"
        OPENAI_API_KEY: "test_openai_api_key_placeholder"
        DISCORD_BOT_TOKEN: "test_discord_bot_token_placeholder"
        # Adicione outras variáveis de ambiente que possam ser necessárias para os testes
      run: uv run pytest --cov=src --cov-report=xml --cov-report=term-missing tests/ # Assumes your tests are in the 'tests/' directory

    - name: Upload coverage to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
        if-no-files-found: error # Opcional: falha se o coverage.xml não for encontrado 